name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  call-reusable-workflow:
    uses: thanhtuan-pham/beep_net_pipeline_templates/.github/workflows/create-release.yml@main
    with:
      runner: 'windows-latest'
