name: Create Release

on:
  push:
    branches: 
    - '*'
    - '!release'
    
  pull_request:
    branches:
    - '*'
    - '!release'
  #push:
   # tags:
     # - 'v*'
      
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  call-reusable-workflow:
    uses: thanhtuan-pham/beep_net_pipeline_templates/.github/workflows/create-release2.yml@main
