name: Build And Test Project

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - '*'
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
     
jobs:
  call-reusable-workflow:
    uses: thanhtuan-pham/beep_net_pipeline_templates/.github/workflows/beep-build.yml@main
    with:
      results-path: 'src/**/*.trx'
