name: Publish NuGet Package

on:
  release:
        types: [created]

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  call-reusable-workflow:
    uses: thanhtuan-pham/beep_net_pipeline_templates/.github/workflows/publish-nuget.yml@main
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
